# Generated by Django 3.2.13 on 2022-06-08 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0012_post_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marked_Officers_forward',
            fields=[
                ('marked_no_forward', models.BigAutoField(primary_key=True, serialize=False)),
                ('compliance_forward', models.CharField(max_length=10, null=True)),
                ('compliance_recieved_on_forward', models.DateTimeField(null=True)),
                ('modified_on_forward', models.DateTimeField(null=True)),
                ('created_on_forward', models.DateTimeField(null=True)),
                ('modified_by_forward', models.CharField(max_length=10, null=True)),
                ('created_by_forward', models.CharField(max_length=10, null=True)),
                ('marked_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inspects.marked_officers')),
                ('marked_to_forward', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inspects.designation_master')),
            ],
        ),
    ]
