# Generated by Django 3.2.13 on 2022-06-08 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0013_marked_officers_forward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marked_officers',
            name='myuser_id',
        ),
    ]
