# Generated by Django 3.2.13 on 2022-06-09 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0015_marked_officers_myuser_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRMS',
            fields=[
                ('empno', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('empname', models.CharField(max_length=50, null=True)),
                ('pay_level', models.CharField(max_length=10, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('designation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inspects.designation_master')),
            ],
        ),
    ]
