# Generated by Django 3.2.13 on 2022-06-10 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0017_empmast_myuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrms',
            name='div_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='div_id', to='inspects.railwaylocationmaster'),
        ),
        migrations.AddField(
            model_name='hrms',
            name='rly_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rly_id', to='inspects.railwaylocationmaster'),
        ),
    ]
