# Generated by Django 3.2.13 on 2022-06-10 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0018_auto_20220610_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='empmast',
            name='div_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empmast_div_id', to='inspects.railwaylocationmaster'),
        ),
        migrations.AddField(
            model_name='empmast',
            name='rly_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empmast_rly_id', to='inspects.railwaylocationmaster'),
        ),
    ]
