# Generated by Django 3.0 on 2022-06-11 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0019_auto_20220610_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empmast',
            name='myuser_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inspects.MyUser'),
        ),
        migrations.AlterField(
            model_name='marked_officers',
            name='myuser_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inspects.MyUser'),
        ),
    ]
