# Generated by Django 2.0.7 on 2022-06-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0020_auto_20220611_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marked_officers',
            name='myuser_id',
        ),
        migrations.AddField(
            model_name='inspection_details',
            name='target_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='item_details',
            name='item_title',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inspection_details',
            name='dept',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inspection_details',
            name='inspected_on',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='inspection_details',
            name='report_path',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item_details',
            name='status_flag',
            field=models.IntegerField(null=True),
        ),
    ]
