# Generated by Django 3.2.13 on 2022-06-14 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0022_auto_20220614_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection_details',
            name='status_flag',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='marked_officers',
            name='myuser_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
