# Generated by Django 3.2.13 on 2022-06-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0023_auto_20220614_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marked_officers',
            name='compliance',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
