# Generated by Django 3.2 on 2022-06-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0026_alter_item_details_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_details',
            name='target_date',
            field=models.DateField(null=True),
        ),
    ]
