# Generated by Django 3.2 on 2022-06-22 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0027_item_details_target_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='user_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empno', models.IntegerField(null=True)),
                ('requestDate', models.DateField(null=True)),
                ('remarks', models.CharField(max_length=200, null=True)),
                ('request_type', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('myuser_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rly_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empmast_rly_id1', to='inspects.railwaylocationmaster')),
            ],
        ),
    ]
