# Generated by Django 3.2 on 2022-06-27 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0029_alter_railwaylocationmaster_parent_location_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection_Checklist',
            fields=[
                ('checklist_id', models.AutoField(primary_key=True, serialize=False)),
                ('checklist_title', models.CharField(max_length=100)),
                ('inspection_type', models.IntegerField(choices=[('1', 'Station'), ('2', 'Track'), ('3', 'Workshop'), ('4', 'Gate'), ('5', 'Footplate'), ('6', 'RCD')], default='1')),
                ('status', models.CharField(max_length=10)),
                ('delete_flag', models.IntegerField(default=False)),
                ('created_by', models.CharField(max_length=10, null=True)),
                ('created_on', models.DateTimeField(null=True)),
                ('last_modified_by', models.CharField(max_length=10, null=True)),
                ('last_modified_on', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='item_details',
            name='item_link',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='item_details',
            name='item_subtitle',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='item_details',
            name='type',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.CreateModel(
            name='Inspection_Activity',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('activities', models.CharField(max_length=200)),
                ('delete_flag', models.IntegerField(default=False)),
                ('created_by', models.CharField(max_length=10, null=True)),
                ('created_on', models.DateTimeField(null=True)),
                ('last_modified_by', models.CharField(max_length=10, null=True)),
                ('last_modified_on', models.DateTimeField(null=True)),
                ('checklist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspects.inspection_checklist')),
            ],
        ),
    ]
