# Generated by Django 3.2 on 2022-06-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0030_auto_20220627_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection_details',
            name='inspection_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
