# Generated by Django 3.2 on 2022-06-28 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0031_alter_inspection_details_inspection_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hrms',
            name='designation',
        ),
    ]
