# Generated by Django 3.2 on 2022-06-28 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0032_remove_hrms_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrms',
            name='designation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inspects.level_desig'),
        ),
    ]
