# Generated by Django 3.2 on 2022-06-28 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0034_remove_hrms_designation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Level_Desig',
        ),
    ]
