# Generated by Django 3.2 on 2022-06-28 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0015_divisonmaster'),
        ('inspects', '0035_delete_level_desig'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrms',
            name='designation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.level_desig'),
        ),
    ]
