# Generated by Django 3.2 on 2022-06-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0037_alter_user_request_empno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_request',
            name='empno',
            field=models.BigIntegerField(max_length=12, null=True),
        ),
    ]
