# Generated by Django 3.2 on 2022-06-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspects', '0039_auto_20220628_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_details',
            name='des_id',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
