# Generated by Django 2.0.7 on 2022-06-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='railwayLocationMaster',
            fields=[
                ('rly_unit_code', models.AutoField(primary_key=True, serialize=False)),
                ('location_code', models.CharField(max_length=10, null=True)),
                ('location_type', models.CharField(max_length=5, null=True)),
                ('location_description', models.CharField(max_length=50)),
                ('parent_location_code', models.CharField(max_length=5)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(max_length=30, null=True)),
                ('station_code', models.CharField(max_length=5, null=True)),
                ('rstype', models.CharField(max_length=15, null=True)),
                ('location_type_desc', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
