# Generated by Django 2.0.7 on 2022-06-09 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_empmast'),
    ]

    operations = [
        migrations.CreateModel(
            name='departMast',
            fields=[
                ('department_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('department_name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('delete_flag', models.BooleanField(default=False)),
                ('modified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('rly_unit_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.railwayLocationMaster')),
            ],
        ),
    ]
