# Generated by Django 2.0.7 on 2022-06-09 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_departmast'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_master',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_desc', models.CharField(blank=True, max_length=50, null=True)),
                ('delete_flag', models.BooleanField(default=False)),
                ('modified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('department_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.departMast')),
                ('rly_unit_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.railwayLocationMaster')),
            ],
        ),
    ]
