# Generated by Django 2.0.7 on 2022-06-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0006_roless'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmast',
            name='delete_flag',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='empmast',
            name='profile_modified_on',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='roless',
            name='delete_flag',
            field=models.NullBooleanField(default=False),
        ),
    ]
