# Generated by Django 2.0.7 on 2022-06-10 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0007_auto_20220610_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop_section',
            fields=[
                ('section_code', models.CharField(max_length=10)),
                ('section_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('section_desc', models.CharField(max_length=150, null=True)),
                ('shop_code', models.CharField(max_length=50, null=True)),
                ('shop_id', models.CharField(max_length=50, null=True)),
                ('flag', models.CharField(max_length=1, null=True)),
                ('rly_unit_code', models.CharField(blank=True, max_length=3, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('department_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myadmin.departMast')),
            ],
        ),
    ]
