# Generated by Django 2.0.7 on 2022-06-14 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0011_designation_master_inspection_details_item_details_marked_officers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_details',
            name='inspection_no',
        ),
        migrations.RemoveField(
            model_name='marked_officers',
            name='item_no',
        ),
        migrations.RemoveField(
            model_name='marked_officers',
            name='marked_to',
        ),
        migrations.DeleteModel(
            name='Designation_Master',
        ),
        migrations.DeleteModel(
            name='Inspection_details',
        ),
        migrations.DeleteModel(
            name='Item_details',
        ),
        migrations.DeleteModel(
            name='Marked_Officers',
        ),
    ]
