# Generated by Django 3.2 on 2022-06-24 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0012_auto_20220614_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='locationMaster',
            fields=[
                ('pincode', models.IntegerField(primary_key=True, serialize=False)),
                ('district', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(default='NA', max_length=50)),
            ],
            options={
                'db_table': 'locationMaster',
            },
        ),
        migrations.CreateModel(
            name='headquarterMaster',
            fields=[
                ('headquarter_code', models.BigAutoField(primary_key=True, serialize=False)),
                ('headquarter_address', models.CharField(max_length=100)),
                ('headquarter_admin', models.CharField(max_length=30)),
                ('admin_mobile', models.BigIntegerField(unique=True)),
                ('admin_phone', models.CharField(max_length=12, null=True)),
                ('admin_email', models.EmailField(max_length=254, unique=True)),
                ('headquarter_status', models.CharField(max_length=10)),
                ('headquarter_rly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.railwaylocationmaster')),
                ('pincode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.locationmaster')),
            ],
            options={
                'db_table': 'headquarterMaster',
            },
        ),
    ]
