# Generated by Django 3.2 on 2022-06-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0013_headquartermaster_locationmaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='railwaylocationmaster',
            name='parent_location_code',
            field=models.CharField(max_length=10),
        ),
    ]
