# Generated by Django 3.2 on 2022-06-27 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0014_alter_railwaylocationmaster_parent_location_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='divisonMaster',
            fields=[
                ('divison_code', models.BigAutoField(primary_key=True, serialize=False)),
                ('divison_address', models.CharField(max_length=100)),
                ('divison_admin', models.CharField(max_length=30)),
                ('admin_mobile', models.BigIntegerField(unique=True)),
                ('admin_phone', models.CharField(max_length=12, null=True)),
                ('admin_email', models.EmailField(max_length=254, unique=True)),
                ('divison_status', models.CharField(max_length=10)),
                ('divison_rly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.railwaylocationmaster')),
                ('pincode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.locationmaster')),
            ],
            options={
                'db_table': 'divisonMaster',
            },
        ),
    ]
